"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Sequelize = require("sequelize");
const errors_1 = require("../errors");
const config_1 = require("../../core/config");
const reference_1 = require("../reference");
const user_1 = require("./user");
const attributes = {
    user: {
        type: Sequelize.UUID,
        references: {
            model: user_1.default,
            key: 'id',
            onUpdate: 'cascade',
            onDelete: 'cascade'
        },
        primaryKey: true
    },
    // The following indicate whether the user can teach the following subjects.
    'english:americanLiterature': Sequelize.BOOLEAN,
    'english:britishLiterature': Sequelize.BOOLEAN,
    'english:contemporaryLiterature': Sequelize.BOOLEAN,
    'english:creativeWriting': Sequelize.BOOLEAN,
    'english:englishLanguageAndComposition': Sequelize.BOOLEAN,
    'english:englishLiteratureAndComposition': Sequelize.BOOLEAN,
    'english:literaryAnalysis': Sequelize.BOOLEAN,
    'english:modernLiterature': Sequelize.BOOLEAN,
    'english:poetry': Sequelize.BOOLEAN,
    'english:worldLiterature': Sequelize.BOOLEAN,
    'english:writtenAndOralCommunication': Sequelize.BOOLEAN,
    'english:apEnglishLanguageAndComposition': Sequelize.BOOLEAN,
    'english:apEnglishLiteratureAndComposition': Sequelize.BOOLEAN,
    'foreignLanguage:americanSignLanguage': Sequelize.BOOLEAN,
    'foreignLanguage:ancientGreek': Sequelize.BOOLEAN,
    'foreignLanguage:arabic': Sequelize.BOOLEAN,
    'foreignLanguage:chinese': Sequelize.BOOLEAN,
    'foreignLanguage:french': Sequelize.BOOLEAN,
    'foreignLanguage:german': Sequelize.BOOLEAN,
    'foreignLanguage:hebrew': Sequelize.BOOLEAN,
    'foreignLanguage:italian': Sequelize.BOOLEAN,
    'foreignLanguage:japanese': Sequelize.BOOLEAN,
    'foreignLanguage:korean': Sequelize.BOOLEAN,
    'foreignLanguage:latin': Sequelize.BOOLEAN,
    'foreignLanguage:portuguese': Sequelize.BOOLEAN,
    'foreignLanguage:russian': Sequelize.BOOLEAN,
    'foreignLanguage:spanish': Sequelize.BOOLEAN,
    'foreignLanguage:apChineseLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apFrenchLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apGermanLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apItalianLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apJapaneseLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apLatin': Sequelize.BOOLEAN,
    'foreignLanguage:apSpanishLanguageAndCulture': Sequelize.BOOLEAN,
    'foreignLanguage:apSpanishLiteratureAndCulture': Sequelize.BOOLEAN,
    'math:algebra1': Sequelize.BOOLEAN,
    'math:algebra2': Sequelize.BOOLEAN,
    'math:calculus': Sequelize.BOOLEAN,
    'math:geometry': Sequelize.BOOLEAN,
    'math:multivariableCalculus': Sequelize.BOOLEAN,
    'math:practicalMath': Sequelize.BOOLEAN,
    'math:preAlgebra': Sequelize.BOOLEAN,
    'math:preCalculus': Sequelize.BOOLEAN,
    'math:probability': Sequelize.BOOLEAN,
    'math:quantitativeLiteracy': Sequelize.BOOLEAN,
    'math:statistics': Sequelize.BOOLEAN,
    'math:trigonometry': Sequelize.BOOLEAN,
    'math:apCalculusAb': Sequelize.BOOLEAN,
    'math:apCalculusBc': Sequelize.BOOLEAN,
    'math:apStatistics': Sequelize.BOOLEAN,
    'computerScience:apComputerScienceA': Sequelize.BOOLEAN,
    'computerScience:apComputerSciencePrinciples': Sequelize.BOOLEAN,
    'science:biology': Sequelize.BOOLEAN,
    'science:chemistry': Sequelize.BOOLEAN,
    'science:earthScience': Sequelize.BOOLEAN,
    'science:environmentalScience': Sequelize.BOOLEAN,
    'science:environmentalStudies': Sequelize.BOOLEAN,
    'science:forensicScience': Sequelize.BOOLEAN,
    'science:geology': Sequelize.BOOLEAN,
    'science:marineBiology': Sequelize.BOOLEAN,
    'science:physicalScience': Sequelize.BOOLEAN,
    'science:physics': Sequelize.BOOLEAN,
    'science:apBiology': Sequelize.BOOLEAN,
    'science:apChemistry': Sequelize.BOOLEAN,
    'science:apEnvironmentalScience': Sequelize.BOOLEAN,
    'science:apPhysicsCMechanics': Sequelize.BOOLEAN,
    'science:apPhysicsCElectricityAndMagnetism': Sequelize.BOOLEAN,
    'science:apPhysics1AlgebraBased': Sequelize.BOOLEAN,
    'science:apPhysics2AlgebraBased': Sequelize.BOOLEAN,
    'socialStudies:culturalAnthropology': Sequelize.BOOLEAN,
    'socialStudies:currentEvents': Sequelize.BOOLEAN,
    'socialStudies:europeanHistory': Sequelize.BOOLEAN,
    'socialStudies:geography': Sequelize.BOOLEAN,
    'socialStudies:globalStudies': Sequelize.BOOLEAN,
    'socialStudies:humanGeography': Sequelize.BOOLEAN,
    'socialStudies:internationalRelations': Sequelize.BOOLEAN,
    'socialStudies:law': Sequelize.BOOLEAN,
    'socialStudies:macroeconomics': Sequelize.BOOLEAN,
    'socialStudies:microeconomics': Sequelize.BOOLEAN,
    'socialStudies:modernWorldStudies': Sequelize.BOOLEAN,
    'socialStudies:physicalAnthropology': Sequelize.BOOLEAN,
    'socialStudies:politicalStudies': Sequelize.BOOLEAN,
    'socialStudies:psychology': Sequelize.BOOLEAN,
    'socialStudies:religiousStudies': Sequelize.BOOLEAN,
    'socialStudies:sociology': Sequelize.BOOLEAN,
    'socialStudies:usGovernment': Sequelize.BOOLEAN,
    'socialStudies:usHistory': Sequelize.BOOLEAN,
    'socialStudies:womensStudies': Sequelize.BOOLEAN,
    'socialStudies:worldHistory': Sequelize.BOOLEAN,
    'socialStudies:worldPolitics': Sequelize.BOOLEAN,
    'socialStudies:worldReligions': Sequelize.BOOLEAN,
    'socialStudies:apComparativeGovernmentAndPolitics': Sequelize.BOOLEAN,
    'socialStudies:apEuropeanHistory': Sequelize.BOOLEAN,
    'socialStudies:apHumanGeography': Sequelize.BOOLEAN,
    'socialStudies:apMacroeconomics': Sequelize.BOOLEAN,
    'socialStudies:apMicroeconomics': Sequelize.BOOLEAN,
    'socialStudies:apPsychology': Sequelize.BOOLEAN,
    'socialStudies:apUnitedStatesGovernmentAndPolitics': Sequelize.BOOLEAN,
    'socialStudies:apUnitedStatesHistory': Sequelize.BOOLEAN,
    'socialStudies:apWorldHistory': Sequelize.BOOLEAN
};
const blockUserEdit = (instance) => {
    if (instance.changed('user')) {
        throw new errors_1.ProhibitedEditError('Editing the user FK of mentors table is prohibited.');
    }
};
const model = reference_1.sequelizeAdmin.define('mentors', attributes);
model.beforeUpdate(blockUserEdit);
model.sync({ alter: config_1.default.devMode }); // Alter when in development mode
exports.default = model;
//# sourceMappingURL=mentor.js.map