export default {
	INIT_START: 'INIT_START',
	INIT_END: 'INIT_END',
	
	INIT_CONFIG: 'INIT_CONFIG',
	
	INIT_USER: 'INIT_USER',
	CLEAR_USER: 'CLEAR_USER',
	
	SOCKET_CONNECT: 'SOCKET_CONNECT',
	
	EDIT_ACCOUNT: 'EDIT_ACCOUNT',
	EDIT_COMMUNICATIONS: 'EDIT_COMMUNICATIONS',
	EDIT_PROFILE: 'EDIT_PROFILE',
	
	UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
	CLOSE_UNEXPECTED_ERROR: 'CLOSE_UNEXPECTED_ERROR',
	IGNORE_UNEXPECTED_ERROR: 'IGNORE_UNEXPECTED_ERROR'
};
